"""empty message

Revision ID: 331b2aa54d85
Revises: 6e523d21793a
Create Date: 2023-11-25 15:01:55.598279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331b2aa54d85'
down_revision = '6e523d21793a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentname_katakana', sa.String(), nullable=True))
        batch_op.drop_index('ix_students_studentname_hiragana')
        batch_op.create_index(batch_op.f('ix_students_studentname_katakana'), ['studentname_katakana'], unique=False)
        batch_op.drop_column('studentname_hiragana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentname_hiragana', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_students_studentname_katakana'))
        batch_op.create_index('ix_students_studentname_hiragana', ['studentname_hiragana'], unique=False)
        batch_op.drop_column('studentname_katakana')

    # ### end Alembic commands ###
