"""empty message

Revision ID: 6e523d21793a
Revises: 
Create Date: 2023-10-22 16:55:20.220918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e523d21793a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administratorname', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrators_administratorname'), ['administratorname'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentname', sa.String(), nullable=True),
    sa.Column('studentname_hiragana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_studentname'), ['studentname'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_studentname_hiragana'), ['studentname_hiragana'], unique=False)

    op.create_table('student_month_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('studentname', sa.String(), nullable=True),
    sa.Column('year_month', sa.String(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('studentname', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('study_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_records')
    op.drop_table('student_month_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_studentname_hiragana'))
        batch_op.drop_index(batch_op.f('ix_students_studentname'))

    op.drop_table('students')
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrators_administratorname'))

    op.drop_table('administrators')
    # ### end Alembic commands ###
